export const basicButtonText = 'import { Button } from "../button";' + '\n'
  + '' + '\n'
  + '' + '\n'
  + 'export const BasicButton = () => {' + '\n'
  + '  return (' + '\n'
  + '    <div className="w-full flex items-center justify-center">' + '\n'
  + '      <Button className="bg-white w-[8rem] h-[2.5rem] text-black hover:bg-gray-300">' + '\n'
  + '        Click me' + '\n'
  + '      </Button>' + '\n'
  + '' + '\n'
  + '    </div>' + '\n'
  + '' + '\n'
  + '  )' + '\n'
  + '}'

export const hoverButtonText = 'import { Button } from "../button";' + '\n'
  + '' + '\n'
  + '' + '\n'
  + 'export const HoverButton = () => {' + '\n'
  + '  return (' + '\n'
  + '    <div className="w-full flex items-center justify-center">' + '\n'
  + '      <Button className="bg-white  w-[8rem] h-[2.5rem]  text-black hover:bg-gray-300 duration-100 transition ease-in hover:translate-y-2">' + '\n'
  + '        Click me' + '\n'
  + '      </Button>' + '\n'
  + '' + '\n'
  + '' + '\n'
  + '    </div>' + '\n'
  + '' + '\n'
  + '  )' + '\n'
  + '}'

export const ringFocusedButtonText = 'import { Button } from "../button";' + '\n'
  + '' + '\n'
  + '' + '\n'
  + 'export const RingFocusedButton = () => {' + '\n'
  + '  return (' + '\n'
  + '    <div className="w-full flex items-center justify-center">' + '\n'
  + '      <Button className=" text-black  w-[8rem] h-[2.5rem]  bg-white hover:bg-gray-200 focus:ring-2 focus:ring-gray-900 focus:ring-opacity-50 focus:ring-offset-2">' + '\n'
  + '        Click me' + '\n'
  + '      </Button>' + '\n'
  + '' + '\n'
  + '' + '\n'
  + '    </div>' + '\n'
  + '' + '\n'
  + '  )' + '\n'
  + '}'

export const roundedButtonText = 'import { Button } from "../button";' + '\n'
  + '' + '\n'
  + '' + '\n'
  + 'export const RoundedButton = () => {' + '\n'
  + '  return (' + '\n'
  + '    <div className="w-full flex items-center justify-center">' + '\n'
  + '      <Button className="bg-white t w-[8rem] h-[2.5rem]  text-black hover:bg-gray-300 rounded-xl shadow-md">' + '\n'
  + '        Click me' + '\n'
  + '      </Button>' + '\n'
  + '' + '\n'
  + '' + '\n'
  + '    </div>' + '\n'
  + '' + '\n'
  + '  )' 
