export const landingPageText = '"use client";' + '\n'
  + '' + '\n'
  + 'import { BasicAnimation } from "../animations/basicAnimation";' + '\n'
  + '' + '\n'
  + 'const Landing = () => {' + '\n'
  + '  return (' + '\n'
  + '    <div className="min-h-screen">' + '\n'
  + '      <h1 className="text-4xl font-bold bg-gradient-to-r from-blue-200 to-blue-800 bg-clip-text text-transparent">' + '\n'
  + '        <strong>Landing Page</strong>' + '\n'
  + '      </h1>' + '\n'
  + '      <section>' + '\n'
  + '        <p className="w-1/2 mt-3 opacity-30 text-white font-semibold text-md">' + '\n'
  + '          Lorem ipsum odor amet, consectetuer adipiscing elit. Vivamus interdum' + '\n'
  + '          senectus viverra integer tortor blandit. Sed ac etiam sociosqu' + '\n'
  + '          curabitur facilisi odio in sapien. Iaculis ornare risus eget tempus' + '\n'
  + '          morbi, consectetur malesuad' + '\n'
  + '        </p>' + '\n'
  + '' + '\n'
  + '        <BasicAnimation boxes={[1, 2, 3]} />' + '\n'
  + '      </section>' + '\n'
  + '' + '\n'
  + '' + '\n'
  + '    </div>' + '\n'
  + '  );' + '\n'
  + '};' + '\n'
  + 'export default Landing;'
