export const landingPageText = '"use client";' + '\n'
  + '' + '\n'
  + 'import { NewDemoAnimation } from "../animations/demoAnimation";' + '\n'
  + '' + '\n'
  + 'const Landing = () => {' + '\n'
  + '  return (' + '\n'
  + '    <div className="min-h-screen">' + '\n'
  + '      <h1 className="text-4xl font-bold bg-gradient-to-r from-blue-200 to-blue-800 bg-clip-text text-transparent">' + '\n'
  + '        <strong>Landing Page</strong>' + '\n'
  + '      </h1>' + '\n'
  + '      <section>' + '\n'
  + '        <p className="w-1/2 mt-3 opacity-30 text-white font-semibold text-md">' + '\n'
  + '          Lorem ipsum odor amet, consectetuer adipiscing elit. Vivamus interdum' + '\n'
  + '          senectus viverra integer tortor blandit. Sed ac etiam sociosqu' + '\n'
  + '          curabitur facilisi odio in sapien. Iaculis ornare risus eget tempus' + '\n'
  + '          morbi, consectetur malesuad' + '\n'
  + '        </p>' + '\n'
  + '' + '\n'
  + '        <NewDemoAnimation/>' + '\n'
  + '      </section>' + '\n'
  + '' + '\n'
  + '    </div>' + '\n'
  + '  );' + '\n'
  + '};' + '\n'
  + 'export default Landing;'


export const newDemoComponent ='"use client"'+'\n'
+'import gsap from "gsap";'+'\n'
+'import { useRef } from "react";'+'\n'
+'import { useGSAP } from "@gsap/react";'+'\n'
+''+'\n'
+''+'\n'
+'export const NewDemoAnimation = () => {'+'\n'
+'  const containerRef = useRef<HTMLDivElement>(null);'+'\n'
+'  const secondRef = useRef<HTMLDivElement>(null);'+'\n'
+'  const thirdRef = useRef<HTMLDivElement>(null);'+'\n'
+''+'\n'
+'  const fourthRef = useRef<HTMLDivElement>(null);'+'\n'
+''+'\n'
+'  const parentRef = useRef<HTMLDivElement>(null);'+'\n'
+''+'\n'
+'  useGSAP(() => {'+'\n'
+'    const tl = gsap.timeline();'+'\n'
+'    tl.fromTo(parentRef.current, {'+'\n'
+'      y: 300,'+'\n'
+'      opacity: 0'+'\n'
+'    }, {'+'\n'
+'      y: 50,'+'\n'
+'      opacity: 1,'+'\n'
+'      duration: 1.2,'+'\n'
+'      ease: "power2.inOut",'+'\n'
+'    })'+'\n'
+''+'\n'
+'    tl.fromTo([containerRef.current, secondRef.current, thirdRef.current, fourthRef.current], {'+'\n'
+'      y: 20,'+'\n'
+'      opacity: 0'+'\n'
+'    }, {'+'\n'
+'      y: 0,'+'\n'
+'      opacity: 1,'+'\n'
+'      duration: 0.5,'+'\n'
+'      ease: "power1.inOut",'+'\n'
+'      scale: 1,'+'\n'
+'      stagger: 0.25'+'\n'
+''+'\n'
+'    }, "-=1.2")'+'\n'
+''+'\n'
+''+'\n'
+'  }, { scope: parentRef })'+'\n'
+''+'\n'
+'  return ('+'\n'
+'    <div ref={parentRef} >'+'\n'
+'      <div ref={containerRef} className="grid grid-cols-2 gap-8">'+'\n'
+''+'\n'
+''+'\n'
+'        <div className=" flex flex-col items-center p-2  justify-center max-w-6xl h-[7rem] bg-blue-600 hover:border-white hover:bg-blue-400 rounded-lg shadow-lg  hover:cursor-pointer duration-100 transition ease-in hover:translate-y-2  ">'+'\n'
+'          <h2 className="text-white font-bold text-2xl ">Feature 1</h2>'+'\n'
+'        </div>'+'\n'
+''+'\n'
+'        <div className=" flex flex-col items-center justify-center max-w-6xl h-[7rem]  bg-blue-600 hover:border-white hover:bg-blue-400  rounded-lg shadow-lg duration-100 transition ease-in hover:translate-y-2 hover:cursor-pointer ">'+'\n'
+'          <h2 className="text-white font-bold text-2xl ">Feature 2</h2>'+'\n'
+''+'\n'
+'        </div>'+'\n'
+''+'\n'
+''+'\n'
+'      </div>'+'\n'
+''+'\n'
+'      <div className="grid grid-cols-3 gap-8 mt-10" >'+'\n'
+'        <div ref={secondRef} className=" flex flex-col items-center p-2  justify-center max-w-4xl h-[7rem]  bg-blue-600 hover:border-white hover:bg-blue-400   rounded-lg shadow-lg duration-100 transition ease-in hover:translate-y-2 hover:cursor-pointer">'+'\n'
+'          <h2 className="text-white font-bold text-2xl ">Feature 3</h2>'+'\n'
+'        </div>'+'\n'
+''+'\n'
+'        <div ref={thirdRef} className=" flex flex-col items-center justify-center max-w-4xl h-[7rem]  bg-blue-600 hover:border-white hover:bg-blue-400  rounded-lg shadow-lg duration-100 transition ease-in hover:translate-y-2 hover:cursor-pointer">'+'\n'
+'          <h2 className="text-white font-bold text-2xl ">Feature 4</h2>'+'\n'
+'        </div>'+'\n'
+''+'\n'
+'        <div ref={fourthRef} className=" flex flex-col items-center justify-center max-w-4xl h-[7rem]  bg-blue-600 hover:border-white hover:bg-blue-400   shadow-lg rounded-lg duration-100 transition ease-in hover:translate-y-2 hover:cursor-pointer">'+'\n'
+'          <h2 className="text-white font-bold text-2xl ">Feature 5</h2>'+'\n'
+''+'\n'
+'        </div>'+'\n'
+'      </div>'+'\n'
+''+'\n'
+'    </div>'+'\n'
+'  )'+'\n'
+''+'\n'
+'}'
