export const welcome = 'import { useRef } from "react"' + '\n'
  + 'import { useGSAP } from "@gsap/react"' + '\n'
  + 'import { gsap } from "gsap";' + '\n'

  + '\n' + 'export const WelcomeComponent = () => {' + '\n'
  + '  const containerRef = useRef<HTMLDivElement>(null);' + '\n'
  + '  const firstRef = useRef<HTMLDivElement>(null);' + '\n'
  + '  const secondRef = useRef<HTMLDivElement>(null);' + '\n'
  + '  const thirdRef = useRef<HTMLDivElement>(null)' + '\n'
  + '' + '\n'
  + '  useGSAP(() => {' + '\n'
  + '    const tl = gsap.timeline({' + '\n'
  + '      yoyo: true,' + '\n'
  + '      repeat: -1' + '\n'
  + '    });' + '\n'
  + '' + '\n'
  + '    tl.fromTo(containerRef.current, {' + '\n'
  + '      y: 300,' + '\n'
  + '      opacity: 0' + '\n'
  + '    }, {' + '\n'
  + '      opacity: 1,' + '\n'
  + '      y: 50,' + '\n'
  + '      ease: "back.out(1.7)",' + '\n'
  + '      duration: 1' + '\n'
  + '    })' + '\n'
  + '' + '\n'
  + '    tl.fromTo([firstRef.current, secondRef.current, thirdRef.current], {' + '\n'
  + '      y: 20,' + '\n'
  + '      opacity: 0' + '\n'
  + '    }, {' + '\n'
  + '      y: 0,' + '\n'
  + '      opacity: 1,' + '\n'
  + '      ease: "back.out(1.7)",' + '\n'
  + '      duration: 1.2,' + '\n'
  + '      stagger: 0.2' + '\n'
  + '    }, "-=1")' + '\n'
  + '' + '\n'
  + '' + '\n'
  + '  })' + '\n'
  + '  return (' + '\n'
  + '    <div ref={containerRef} className="flex flex-row gap-2" >' + '\n'
  + '      <h2 ref={firstRef} className="font-extrabold bg-gradient-to-br from-blue-800 to-white bg-clip-text text-transparent  text-4xl">Check</h2>' + '\n'
  + '      <h2 ref={secondRef} className="font-extrabold bg-gradient-to-br from-blue-800 to-white bg-clip-text text-transparent  text-4xl">It</h2>' + '\n'
  + '      <h2 ref={thirdRef} className="font-extrabold bg-gradient-to-br from-blue-800 to-white bg-clip-text text-transparent  text-4xl">Out!</h2>' + '\n'
  + '    </div>' + '\n'
  + '  )' + '\n'
  + '}' + '\n'
  + ''


